[project]
name = "smart-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.2",
    "openai>=2.11.0",
    "requests>=2.32.5",
    "yt-dlp>=2025.12.8",
]
